development:
  adapter: postgresql
  encoding: unicode
  database: digVid_development
  pool: 5
  username: urszulakowalska
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: digVid_production
  host: localhost

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
